go-server:
  image: "gocd/gocd-server:v17.3.0"
  ports:
    - "8153:8153"
    - "8154:8154"
  volumes:
    - ./cruise-config.xml:/godata/config/cruise-config.xml

go-agent:
  image: "gocd/gocd-agent-alpine-3.5:v17.3.0"
  links:
    - go-server:go-server
  environment:
    GO_SERVER_URL: "https://go-server:8154/go"
    AGENT_AUTO_REGISTER_KEY: "verysecurekey"
    AGENT_AUTO_REGISTER_RESOURCES: "gocd"
    AGENT_AUTO_REGISTER_HOSTNAME: "go-agent"
